### ISSUE TITLE
Fix imports in browser projects

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface.js#137]
For examples, add `@huggingface/hub` to a sveltekit project, and add this in `+page.svelte`:

```ts
	onMount(async () => {
		for await (const file of listFiles({ repo: 'gpt2' })) {
			console.log(file);
		}
	});
```

- during `pnpm dev`, it works fine
- during `pnpm build`, it doesn't! Tries to bundle `sha256-node`

```console
error during build:
RollupError: "createHash" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/@huggingface+hub@0.5.0/node_modules/@huggingface/hub/dist/sha256-node-FNR7GJ4E.mjs".
    at error (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:2041:30)
    at Module.error (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:13062:16)
    at Module.traceVariable (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:13445:29)
    at ModuleScope.findVariable (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:11926:39)
    at FunctionScope.findVariable (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:6761:38)
    at ChildScope.findVariable (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:6761:38)
    at Identifier.bind (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:7855:40)
    at CallExpression.bind (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:5653:23)
    at CallExpression.bind (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:9382:15)
    at VariableDeclarator.bind (file:///home/project/node_modules/.pnpm/rollup@3.10.1/node_modules/rollup/dist/es/shared/rollup.js:5653:23)
 ELIFECYCLE  Command failed with exit code 1.
```

Maybe what you encounter in https://github.com/huggingface/huggingface.js/pull/121#discussion_r1163381472 @Aschen

**Comment by coyotte508** [comment]
https://nodejs.org/api/packages.html#nested-conditions

Maybe it could be fixed by having a "node" section in the exports alongside regular exports. And we could use https://www.npmjs.com/package/rollup-plugin-ignore depending on the target

**Comment by HelloRWA** [comment]
in your vite config

`
 resolve: {
    alias: {
      crypto: 'crypto-browserify',
    },
  },
`

**Comment by fronkcoin** [comment]
> in your vite config
> 
> ```
>  resolve: {
>     alias: {
>       crypto: 'crypto-browserify',
>     },
>   },
> ```

Thank you!

**Comment by IlyaSemenov** [comment]
There's also `vite-plugin-node-polyfills` which is an umbrella plugin for buffer, crypto, zlib, etc. polyfills.
