### ISSUE TITLE
[Network issue] - 400 Client Error: Bad Request for url: https://s3.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by ParseDark** [huggingface/huggingface.js#209]
I create a huggingface node in flowise. But the huggingface node look like always the the 400 error. 

```
Error: 400 Client Error: Bad Request for url: https://s3.us-east-1.amazonaws.com/lfs.huggingface.co/repos/36/2c/362cd4772ca1a9fd07d666e19be9b736df444e38495291ed4d6fb4c4d6d7595d/a8fd120b1a0032e70ff3d4b8ab8e46a6d01c2cb08ffe7c007a021c1788928146
    at HfInference.request (/Users/hawei/.local/opt/node-v18.15.0/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:452:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HfInference.featureExtraction (/Users/hawei/.local/opt/node-v18.15.0/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:291:17)
    at async RetryOperation._fn (/Users/hawei/.local/opt/node-v18.15.0/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}

```

**Comment by coyotte508** [comment]
Where are you running this? what's the version of `@huggingface/inference`?

**Comment by coyotte508** [comment]
And what are you trying to do, can you past the call to the lib?

**Comment by coyotte508** [comment]
It should be fixed!
