### ISSUE TITLE
Lack of 'tojson()' support in Jinja2 package

### ISSUE THREAD

**Issue by KatarinaMah** [huggingface/huggingface.js#839]
I am facing issues trying to use templates that make use of the `tojson()` or `json()` filters.

## System Information
- Windows Version	10.0.22631 Build 22631
- Running Node.JS 20.11 within WSL2 Ubuntu 22.04
- Using `@huggingface/jinja` on version `v0.2.2`

## Steps to reproduce
- Install `@huggingface/jinja` (currently running v0.2.2)
  - `npm i --save @huggingface/jinja`
- Create a new file with the following content
```js
import { Template } from '@huggingface/jinja';

const template = new Template(
    '{{- test|tojson(indent=4)}}');
const result = template.render({
    test: {
        foo: 'bar'
    }
});

console.log(result);
```

### Expected Behavior
It should print a stringified representation of the `test` object passed into the `.render()` method.

### Actual Behavior
The following error occurs
```
/home/kmahlendorf/.nvm/versions/node/v20.11.1/bin/node /home/kmahlendorf/git/testies/test.js
file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1265
        throw new Error(`Cannot apply filter "${filterName}" to type: ${operand.type}`);
              ^

Error: Cannot apply filter "tojson" to type: ObjectValue
    at Interpreter.evaluateFilterExpression (file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1265:15)
    at Interpreter.evaluate (file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1501:21)
    at Interpreter.evaluateBlock (file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1300:34)
    at Interpreter.evalProgram (file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1295:17)
    at Interpreter.evaluate (file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1462:21)
    at Interpreter.run (file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1069:17)
    at Template.render (file:///home/kmahlendorf/git/testies/node_modules/@huggingface/jinja/dist/index.js:1562:32)
    at file:///home/kmahlendorf/git/testies/test.js:5:25
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)

Node.js v20.11.1

Process finished with exit code 1
```

---

This seems to due to a lack of support specifically in [this method of the Interpreter](https://github.com/huggingface/huggingface.js/blob/3f9c0a965e011ab32381eef90d4effc19245f4dc/packages/jinja/src/runtime.ts#L447).

Is this intended or maybe because of a lack of compatibility? I'd be more than grateful for an answer!

**Comment by Vaibhavs10** [comment]
cc: @xenova our jinja expert 🔥

**Comment by xenova** [comment]
Hi there 👋 This was added in `@huggingface/jinja` v0.3.0 👍  Can you upgrade and see if it works correctly?
